"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const jsx_runtime_1 = require("react/jsx-runtime");
const react_router_dom_1 = require("react-router-dom");
const DashboardLayout_1 = require("./components/DashboardLayout");
const JobSearch_1 = require("./components/JobSearch");
const MarketAnalysis_1 = require("./components/MarketAnalysis");
const Dashboard_1 = require("./components/Dashboard");
const JobApplications_1 = require("./components/JobApplications");
const Auth_1 = require("./components/Auth");
const Pricing_1 = require("./components/Pricing");
const Profile_1 = require("./components/Profile");
const PrivacyPolicy_1 = require("./components/PrivacyPolicy");
const PrivacyConsent_1 = require("./components/PrivacyConsent");
const SecurityBadge_1 = require("./components/SecurityBadge");
const ProtectedRoute_1 = require("./components/ProtectedRoute");
const AuthProvider_1 = require("./components/AuthProvider");
const CVBuilder_1 = require("./components/cv/CVBuilder");
const NetworkPage_1 = require("./components/NetworkPage");
const LandingPage_1 = require("./components/LandingPage");
const FeaturesPage_1 = require("./components/pages/FeaturesPage");
const HowItWorksPage_1 = require("./components/pages/HowItWorksPage");
const TestimonialsPage_1 = require("./components/pages/TestimonialsPage");
const ResetPassword_1 = require("./components/ResetPassword");
const AuthCallback_1 = require("./components/AuthCallback");
const FreelanceProjects_1 = require("./components/freelance/FreelanceProjects");
const FreelanceProfile_1 = require("./components/freelance/FreelanceProfile");
const MarketTrendsPage_1 = require("./components/pages/MarketTrendsPage");
const RecruiterDashboard_1 = require("./components/recruiter/RecruiterDashboard");
const CandidateSearch_1 = require("./components/recruiter/CandidateSearch");
const JobPostings_1 = require("./components/recruiter/JobPostings");
const CreateJobPosting_1 = require("./components/recruiter/CreateJobPosting");
const UserTypeSelection_1 = require("./components/UserTypeSelection");
const ErrorBoundary_1 = require("./components/ErrorBoundary");
const StripeCheckoutStatus_1 = require("./components/StripeCheckoutStatus");
const Billing_1 = require("./components/Billing");
const SubscriptionBanner_1 = require("./components/SubscriptionBanner");
function App() {
    return ((0, jsx_runtime_1.jsx)(ErrorBoundary_1.ErrorBoundary, { children: (0, jsx_runtime_1.jsx)(react_router_dom_1.BrowserRouter, { children: (0, jsx_runtime_1.jsxs)(AuthProvider_1.AuthProvider, { children: [(0, jsx_runtime_1.jsxs)(react_router_dom_1.Routes, { children: [(0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/", element: (0, jsx_runtime_1.jsx)(LandingPage_1.LandingPage, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/login", element: (0, jsx_runtime_1.jsx)(Auth_1.Auth, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/pricing", element: (0, jsx_runtime_1.jsx)(Pricing_1.Pricing, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/privacy", element: (0, jsx_runtime_1.jsx)(PrivacyPolicy_1.PrivacyPolicy, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/features", element: (0, jsx_runtime_1.jsx)(FeaturesPage_1.FeaturesPage, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/how-it-works", element: (0, jsx_runtime_1.jsx)(HowItWorksPage_1.HowItWorksPage, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/testimonials", element: (0, jsx_runtime_1.jsx)(TestimonialsPage_1.TestimonialsPage, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/auth/reset-password", element: (0, jsx_runtime_1.jsx)(ResetPassword_1.ResetPassword, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/auth/callback", element: (0, jsx_runtime_1.jsx)(AuthCallback_1.AuthCallback, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/checkout/success", element: (0, jsx_runtime_1.jsx)(StripeCheckoutStatus_1.StripeCheckoutStatus, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/user-type", element: (0, jsx_runtime_1.jsx)(ProtectedRoute_1.ProtectedRoute, { children: (0, jsx_runtime_1.jsx)(UserTypeSelection_1.UserTypeSelection, {}) }) }), (0, jsx_runtime_1.jsxs)(react_router_dom_1.Route, { element: (0, jsx_runtime_1.jsx)(ProtectedRoute_1.ProtectedRoute, { children: (0, jsx_runtime_1.jsx)(DashboardLayout_1.DashboardLayout, {}) }), children: [(0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/dashboard", element: (0, jsx_runtime_1.jsx)(Dashboard_1.Dashboard, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/profile", element: (0, jsx_runtime_1.jsx)(Profile_1.Profile, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/billing", element: (0, jsx_runtime_1.jsx)(Billing_1.Billing, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/jobs", element: (0, jsx_runtime_1.jsx)(ProtectedRoute_1.ProtectedRoute, { requiresSubscription: true, children: (0, jsx_runtime_1.jsx)(JobSearch_1.JobSearch, {}) }) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/applications", element: (0, jsx_runtime_1.jsx)(ProtectedRoute_1.ProtectedRoute, { requiresSubscription: true, children: (0, jsx_runtime_1.jsx)(JobApplications_1.JobApplications, {}) }) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/market-analysis", element: (0, jsx_runtime_1.jsx)(ProtectedRoute_1.ProtectedRoute, { requiresSubscription: true, children: (0, jsx_runtime_1.jsx)(MarketAnalysis_1.MarketAnalysis, {}) }) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/cv-builder", element: (0, jsx_runtime_1.jsx)(ProtectedRoute_1.ProtectedRoute, { requiresSubscription: true, children: (0, jsx_runtime_1.jsx)(CVBuilder_1.CVBuilder, {}) }) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/network", element: (0, jsx_runtime_1.jsx)(ProtectedRoute_1.ProtectedRoute, { requiresSubscription: true, children: (0, jsx_runtime_1.jsx)(NetworkPage_1.NetworkPage, {}) }) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/market-trends", element: (0, jsx_runtime_1.jsx)(ProtectedRoute_1.ProtectedRoute, { requiresSubscription: true, children: (0, jsx_runtime_1.jsx)(MarketTrendsPage_1.MarketTrendsPage, {}) }) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/freelance/projects", element: (0, jsx_runtime_1.jsx)(ProtectedRoute_1.ProtectedRoute, { requiresSubscription: true, children: (0, jsx_runtime_1.jsx)(FreelanceProjects_1.FreelanceProjects, {}) }) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/freelance/profile", element: (0, jsx_runtime_1.jsx)(ProtectedRoute_1.ProtectedRoute, { requiresSubscription: true, children: (0, jsx_runtime_1.jsx)(FreelanceProfile_1.FreelanceProfile, {}) }) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/recruiter/dashboard", element: (0, jsx_runtime_1.jsx)(ProtectedRoute_1.ProtectedRoute, { requiresSubscription: true, children: (0, jsx_runtime_1.jsx)(RecruiterDashboard_1.RecruiterDashboard, {}) }) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/recruiter/candidates", element: (0, jsx_runtime_1.jsx)(ProtectedRoute_1.ProtectedRoute, { requiresSubscription: true, children: (0, jsx_runtime_1.jsx)(CandidateSearch_1.CandidateSearch, {}) }) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/recruiter/job-postings", element: (0, jsx_runtime_1.jsx)(ProtectedRoute_1.ProtectedRoute, { requiresSubscription: true, children: (0, jsx_runtime_1.jsx)(JobPostings_1.JobPostings, {}) }) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/recruiter/create-job", element: (0, jsx_runtime_1.jsx)(ProtectedRoute_1.ProtectedRoute, { requiresSubscription: true, children: (0, jsx_runtime_1.jsx)(CreateJobPosting_1.CreateJobPosting, {}) }) })] })] }), (0, jsx_runtime_1.jsx)(PrivacyConsent_1.PrivacyConsent, {}), (0, jsx_runtime_1.jsx)(SecurityBadge_1.SecurityBadge, {}), (0, jsx_runtime_1.jsx)(SubscriptionBanner_1.SubscriptionBanner, {})] }) }) }));
}
exports.default = App;
