#!/usr/bin/env python3
import json
import os
import glob
import shutil

# Fonction pour charger un fichier JSON existant
def load_json(file_path):
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return {}

# Fonction pour sauvegarder un fichier JSON
def save_json(file_path, data):
    os.makedirs(os.path.dirname(file_path), exist_ok=True)
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

# Structure des traductions pour la section "jobs"
jobs_translations = {
    "en": {
        "jobs": {
            "jobDetails": "Job Details",
            "jobDescription": "Job Description",
            "responsibilities": "Responsibilities",
            "requirements": "Requirements",
            "qualifications": "Qualifications",
            "benefits": "Benefits",
            "aboutCompany": "About the Company",
            "similarJobs": "Similar Jobs",
            "jobNotFound": "Job not found",
            "postedBy": "Posted by",
            "postedOn": "Posted on",
            "applicationsClose": "Applications close",
            "numberOfApplicants": "Number of applicants",
            "employmentType": "Employment Type",
            "fullTime": "Full-time",
            "partTime": "Part-time",
            "contract": "Contract",
            "temporary": "Temporary",
            "internship": "Internship",
            "freelance": "Freelance",
            "workplaceType": "Workplace Type",
            "onSite": "On-site",
            "remote": "Remote",
            "hybrid": "Hybrid",
            "salary": "Salary",
            "salaryRange": "Salary range",
            "competitive": "Competitive",
            "negotiable": "Negotiable",
            "hourly": "Hourly",
            "annually": "Annually",
            "experienceLevel": "Experience Level",
            "entryLevel": "Entry level",
            "midLevel": "Mid level",
            "seniorLevel": "Senior level",
            "executive": "Executive",
            "director": "Director",
            "manager": "Manager",
            "industry": "Industry",
            "companySize": "Company Size",
            "employees": "employees",
            "applicantQualifications": "Applicant Qualifications",
            "education": "Education",
            "experience": "Experience",
            "skills": "Skills",
            "languages": "Languages",
            "apply": "Apply for this job",
            "applyExternal": "Apply on company website",
            "saveJob": "Save job",
            "savedJobs": "Saved jobs",
            "share": "Share",
            "report": "Report this job",
            "close": "Close",
            "viewMore": "View more",
            "viewLess": "View less",
            "jobLocation": "Job Location",
            "jobCategory": "Job Category",
            "jobFunction": "Job Function",
            "datePosted": "Date Posted",
            "today": "Today",
            "yesterday": "Yesterday",
            "lastWeek": "Last week",
            "lastMonth": "Last month",
            "anyTime": "Any time",
            "jobAlert": "Job Alert",
            "createJobAlert": "Create job alert",
            "jobAlertCreated": "Job alert created",
            "receiveJobs": "Receive jobs like this by email",
            "jobSaved": "Job saved",
            "jobUnsaved": "Job removed from saved jobs",
            "jobApplicationSubmitted": "Job application submitted",
            "viewApplication": "View application",
            "backToSearch": "Back to search",
            "matchScore": "Match score",
            "perfectMatch": "Perfect match",
            "goodMatch": "Good match",
            "basicMatch": "Basic match",
            "recommended": "Recommended",
            "applyNow": "Apply now",
            "easyApply": "Easy Apply",
            "alreadyApplied": "Already applied",
            "moreJobs": "More jobs from this company",
            "jobSeekers": "Job seekers",
            "employers": "Employers",
            "postJob": "Post a job",
            "companyReviews": "Company reviews",
            "noJobs": "No jobs found",
            "tryNewSearch": "Try a new search",
            "jobsNearby": "Jobs nearby"
        }
    },
    "fr": {
        "jobs": {
            "jobDetails": "Détails de l'emploi",
            "jobDescription": "Description du poste",
            "responsibilities": "Responsabilités",
            "requirements": "Prérequis",
            "qualifications": "Qualifications",
            "benefits": "Avantages",
            "aboutCompany": "À propos de l'entreprise",
            "similarJobs": "Emplois similaires",
            "jobNotFound": "Emploi non trouvé",
            "postedBy": "Publié par",
            "postedOn": "Publié le",
            "applicationsClose": "Clôture des candidatures",
            "numberOfApplicants": "Nombre de candidats",
            "employmentType": "Type d'emploi",
            "fullTime": "Temps plein",
            "partTime": "Temps partiel",
            "contract": "Contrat",
            "temporary": "Temporaire",
            "internship": "Stage",
            "freelance": "Freelance",
            "workplaceType": "Type de lieu de travail",
            "onSite": "Sur site",
            "remote": "Télétravail",
            "hybrid": "Hybride",
            "salary": "Salaire",
            "salaryRange": "Fourchette de salaire",
            "competitive": "Compétitif",
            "negotiable": "Négociable",
            "hourly": "Horaire",
            "annually": "Annuel",
            "experienceLevel": "Niveau d'expérience",
            "entryLevel": "Débutant",
            "midLevel": "Intermédiaire",
            "seniorLevel": "Senior",
            "executive": "Cadre dirigeant",
            "director": "Directeur",
            "manager": "Manager",
            "industry": "Secteur",
            "companySize": "Taille de l'entreprise",
            "employees": "employés",
            "applicantQualifications": "Qualifications requises",
            "education": "Formation",
            "experience": "Expérience",
            "skills": "Compétences",
            "languages": "Langues",
            "apply": "Postuler à cet emploi",
            "applyExternal": "Postuler sur le site de l'entreprise",
            "saveJob": "Sauvegarder l'offre",
            "savedJobs": "Offres sauvegardées",
            "share": "Partager",
            "report": "Signaler cette offre",
            "close": "Fermer",
            "viewMore": "Voir plus",
            "viewLess": "Voir moins",
            "jobLocation": "Lieu de travail",
            "jobCategory": "Catégorie d'emploi",
            "jobFunction": "Fonction",
            "datePosted": "Date de publication",
            "today": "Aujourd'hui",
            "yesterday": "Hier",
            "lastWeek": "La semaine dernière",
            "lastMonth": "Le mois dernier",
            "anyTime": "N'importe quand",
            "jobAlert": "Alerte emploi",
            "createJobAlert": "Créer une alerte emploi",
            "jobAlertCreated": "Alerte emploi créée",
            "receiveJobs": "Recevoir des offres similaires par e-mail",
            "jobSaved": "Offre sauvegardée",
            "jobUnsaved": "Offre retirée des sauvegardes",
            "jobApplicationSubmitted": "Candidature soumise",
            "viewApplication": "Voir la candidature",
            "backToSearch": "Retour à la recherche",
            "matchScore": "Score de correspondance",
            "perfectMatch": "Correspondance parfaite",
            "goodMatch": "Bonne correspondance",
            "basicMatch": "Correspondance basique",
            "recommended": "Recommandé",
            "applyNow": "Postuler maintenant",
            "easyApply": "Candidature simplifiée",
            "alreadyApplied": "Déjà postulé",
            "moreJobs": "Plus d'offres de cette entreprise",
            "jobSeekers": "Chercheurs d'emploi",
            "employers": "Employeurs",
            "postJob": "Publier une offre",
            "companyReviews": "Avis sur l'entreprise",
            "noJobs": "Aucun emploi trouvé",
            "tryNewSearch": "Essayer une nouvelle recherche",
            "jobsNearby": "Emplois à proximité"
        }
    },
    "de": {
        "jobs": {
            "jobDetails": "Stellendetails",
            "jobDescription": "Stellenbeschreibung",
            "responsibilities": "Verantwortlichkeiten",
            "requirements": "Anforderungen",
            "qualifications": "Qualifikationen",
            "benefits": "Vorteile",
            "aboutCompany": "Über das Unternehmen",
            "similarJobs": "Ähnliche Stellen",
            "jobNotFound": "Stelle nicht gefunden",
            "postedBy": "Veröffentlicht von",
            "postedOn": "Veröffentlicht am",
            "applicationsClose": "Bewerbungsschluss",
            "numberOfApplicants": "Anzahl der Bewerber",
            "employmentType": "Beschäftigungsart",
            "fullTime": "Vollzeit",
            "partTime": "Teilzeit",
            "contract": "Befristet",
            "temporary": "Vorübergehend",
            "internship": "Praktikum",
            "freelance": "Freiberuflich",
            "workplaceType": "Arbeitsplatztyp",
            "onSite": "Vor Ort",
            "remote": "Remote",
            "hybrid": "Hybrid",
            "salary": "Gehalt",
            "salaryRange": "Gehaltsrahmen",
            "competitive": "Wettbewerbsfähig",
            "negotiable": "Verhandelbar",
            "hourly": "Stündlich",
            "annually": "Jährlich",
            "experienceLevel": "Erfahrungsstufe",
            "entryLevel": "Einstiegsniveau",
            "midLevel": "Mittleres Niveau",
            "seniorLevel": "Senior-Niveau",
            "executive": "Führungskraft",
            "director": "Direktor",
            "manager": "Manager",
            "industry": "Branche",
            "companySize": "Unternehmensgröße",
            "employees": "Mitarbeiter",
            "applicantQualifications": "Bewerberqualifikationen",
            "education": "Bildung",
            "experience": "Erfahrung",
            "skills": "Fähigkeiten",
            "languages": "Sprachen",
            "apply": "Auf diese Stelle bewerben",
            "applyExternal": "Auf der Unternehmenswebsite bewerben",
            "saveJob": "Stelle speichern",
            "savedJobs": "Gespeicherte Stellen",
            "share": "Teilen",
            "report": "Diese Stelle melden",
            "close": "Schließen",
            "viewMore": "Mehr anzeigen",
            "viewLess": "Weniger anzeigen",
            "jobLocation": "Arbeitsort",
            "jobCategory": "Stellenkategorie",
            "jobFunction": "Stellenfunktion",
            "datePosted": "Veröffentlichungsdatum",
            "today": "Heute",
            "yesterday": "Gestern",
            "lastWeek": "Letzte Woche",
            "lastMonth": "Letzter Monat",
            "anyTime": "Jederzeit",
            "jobAlert": "Stellenalarm",
            "createJobAlert": "Stellenalarm erstellen",
            "jobAlertCreated": "Stellenalarm erstellt",
            "receiveJobs": "Erhalten Sie ähnliche Stellen per E-Mail",
            "jobSaved": "Stelle gespeichert",
            "jobUnsaved": "Stelle aus gespeicherten Stellen entfernt",
            "jobApplicationSubmitted": "Bewerbung eingereicht",
            "viewApplication": "Bewerbung anzeigen",
            "backToSearch": "Zurück zur Suche",
            "matchScore": "Übereinstimmungswert",
            "perfectMatch": "Perfekte Übereinstimmung",
            "goodMatch": "Gute Übereinstimmung",
            "basicMatch": "Grundlegende Übereinstimmung",
            "recommended": "Empfohlen",
            "applyNow": "Jetzt bewerben",
            "easyApply": "Einfach bewerben",
            "alreadyApplied": "Bereits beworben",
            "moreJobs": "Mehr Stellen von diesem Unternehmen",
            "jobSeekers": "Arbeitssuchende",
            "employers": "Arbeitgeber",
            "postJob": "Stelle veröffentlichen",
            "companyReviews": "Unternehmensbewertungen",
            "noJobs": "Keine Stellen gefunden",
            "tryNewSearch": "Neue Suche starten",
            "jobsNearby": "Stellen in der Nähe"
        }
    },
    "es": {
        "jobs": {
            "jobDetails": "Detalles del empleo",
            "jobDescription": "Descripción del puesto",
            "responsibilities": "Responsabilidades",
            "requirements": "Requisitos",
            "qualifications": "Cualificaciones",
            "benefits": "Beneficios",
            "aboutCompany": "Sobre la empresa",
            "similarJobs": "Empleos similares",
            "jobNotFound": "Empleo no encontrado",
            "postedBy": "Publicado por",
            "postedOn": "Publicado el",
            "applicationsClose": "Cierre de solicitudes",
            "numberOfApplicants": "Número de solicitantes",
            "employmentType": "Tipo de empleo",
            "fullTime": "Tiempo completo",
            "partTime": "Tiempo parcial",
            "contract": "Contrato",
            "temporary": "Temporal",
            "internship": "Prácticas",
            "freelance": "Freelance",
            "workplaceType": "Tipo de lugar de trabajo",
            "onSite": "Presencial",
            "remote": "En remoto",
            "hybrid": "Híbrido",
            "salary": "Salario",
            "salaryRange": "Rango salarial",
            "competitive": "Competitivo",
            "negotiable": "Negociable",
            "hourly": "Por hora",
            "annually": "Anual",
            "experienceLevel": "Nivel de experiencia",
            "entryLevel": "Nivel inicial",
            "midLevel": "Nivel medio",
            "seniorLevel": "Nivel senior",
            "executive": "Ejecutivo",
            "director": "Director",
            "manager": "Gerente",
            "industry": "Industria",
            "companySize": "Tamaño de la empresa",
            "employees": "empleados",
            "applicantQualifications": "Cualificaciones del solicitante",
            "education": "Educación",
            "experience": "Experiencia",
            "skills": "Habilidades",
            "languages": "Idiomas",
            "apply": "Solicitar este empleo",
            "applyExternal": "Solicitar en el sitio web de la empresa",
            "saveJob": "Guardar empleo",
            "savedJobs": "Empleos guardados",
            "share": "Compartir",
            "report": "Reportar este empleo",
            "close": "Cerrar",
            "viewMore": "Ver más",
            "viewLess": "Ver menos",
            "jobLocation": "Ubicación del empleo",
            "jobCategory": "Categoría de empleo",
            "jobFunction": "Función del empleo",
            "datePosted": "Fecha de publicación",
            "today": "Hoy",
            "yesterday": "Ayer",
            "lastWeek": "Última semana",
            "lastMonth": "Último mes",
            "anyTime": "Cualquier momento",
            "jobAlert": "Alerta de empleo",
            "createJobAlert": "Crear alerta de empleo",
            "jobAlertCreated": "Alerta de empleo creada",
            "receiveJobs": "Recibir empleos similares por correo electrónico",
            "jobSaved": "Empleo guardado",
            "jobUnsaved": "Empleo eliminado de guardados",
            "jobApplicationSubmitted": "Solicitud de empleo enviada",
            "viewApplication": "Ver solicitud",
            "backToSearch": "Volver a la búsqueda",
            "matchScore": "Puntuación de coincidencia",
            "perfectMatch": "Coincidencia perfecta",
            "goodMatch": "Buena coincidencia",
            "basicMatch": "Coincidencia básica",
            "recommended": "Recomendado",
            "applyNow": "Solicitar ahora",
            "easyApply": "Solicitud fácil",
            "alreadyApplied": "Ya solicitado",
            "moreJobs": "Más empleos de esta empresa",
            "jobSeekers": "Buscadores de empleo",
            "employers": "Empleadores",
            "postJob": "Publicar un empleo",
            "companyReviews": "Opiniones de la empresa",
            "noJobs": "No se encontraron empleos",
            "tryNewSearch": "Probar una nueva búsqueda",
            "jobsNearby": "Empleos cercanos"
        }
    },
    "it": {
        "jobs": {
            "jobDetails": "Dettagli del lavoro",
            "jobDescription": "Descrizione del lavoro",
            "responsibilities": "Responsabilità",
            "requirements": "Requisiti",
            "qualifications": "Qualifiche",
            "benefits": "Benefici",
            "aboutCompany": "Informazioni sull'azienda",
            "similarJobs": "Lavori simili",
            "jobNotFound": "Lavoro non trovato",
            "postedBy": "Pubblicato da",
            "postedOn": "Pubblicato il",
            "applicationsClose": "Chiusura candidature",
            "numberOfApplicants": "Numero di candidati",
            "employmentType": "Tipo di impiego",
            "fullTime": "Tempo pieno",
            "partTime": "Part-time",
            "contract": "Contratto",
            "temporary": "Temporaneo",
            "internship": "Stage",
            "freelance": "Freelance",
            "workplaceType": "Tipo di luogo di lavoro",
            "onSite": "In sede",
            "remote": "Da remoto",
            "hybrid": "Ibrido",
            "salary": "Stipendio",
            "salaryRange": "Fascia di stipendio",
            "competitive": "Competitivo",
            "negotiable": "Negoziabile",
            "hourly": "Orario",
            "annually": "Annuale",
            "experienceLevel": "Livello di esperienza",
            "entryLevel": "Livello base",
            "midLevel": "Livello intermedio",
            "seniorLevel": "Livello senior",
            "executive": "Dirigente",
            "director": "Direttore",
            "manager": "Manager",
            "industry": "Settore",
            "companySize": "Dimensione dell'azienda",
            "employees": "dipendenti",
            "applicantQualifications": "Qualifiche del candidato",
            "education": "Istruzione",
            "experience": "Esperienza",
            "skills": "Competenze",
            "languages": "Lingue",
            "apply": "Candidati per questo lavoro",
            "applyExternal": "Candidati sul sito web dell'azienda",
            "saveJob": "Salva lavoro",
            "savedJobs": "Lavori salvati",
            "share": "Condividi",
            "report": "Segnala questo lavoro",
            "close": "Chiudi",
            "viewMore": "Visualizza di più",
            "viewLess": "Visualizza di meno",
            "jobLocation": "Sede di lavoro",
            "jobCategory": "Categoria di lavoro",
            "jobFunction": "Funzione lavorativa",
            "datePosted": "Data di pubblicazione",
            "today": "Oggi",
            "yesterday": "Ieri",
            "lastWeek": "Ultima settimana",
            "lastMonth": "Ultimo mese",
            "anyTime": "Qualsiasi momento",
            "jobAlert": "Avviso di lavoro",
            "createJobAlert": "Crea avviso di lavoro",
            "jobAlertCreated": "Avviso di lavoro creato",
            "receiveJobs": "Ricevi lavori simili via email",
            "jobSaved": "Lavoro salvato",
            "jobUnsaved": "Lavoro rimosso dai salvati",
            "jobApplicationSubmitted": "Candidatura inviata",
            "viewApplication": "Visualizza candidatura",
            "backToSearch": "Torna alla ricerca",
            "matchScore": "Punteggio di corrispondenza",
            "perfectMatch": "Corrispondenza perfetta",
            "goodMatch": "Buona corrispondenza",
            "basicMatch": "Corrispondenza base",
            "recommended": "Consigliato",
            "applyNow": "Candidati ora",
            "easyApply": "Candidatura facile",
            "alreadyApplied": "Già candidato",
            "moreJobs": "Altri lavori da questa azienda",
            "jobSeekers": "Cercatori di lavoro",
            "employers": "Datori di lavoro",
            "postJob": "Pubblica un lavoro",
            "companyReviews": "Recensioni dell'azienda",
            "noJobs": "Nessun lavoro trovato",
            "tryNewSearch": "Prova una nuova ricerca",
            "jobsNearby": "Lavori nelle vicinanze"
        }
    }
}

# Enrichir les fichiers existants
print("Enrichissement des fichiers de traduction pour la section 'jobs'...")
for lang, content in jobs_translations.items():
    file_path = f"public/locales/{lang}/common.json"
    existing_data = load_json(file_path)
    
    # Fusion des données (priorité aux nouvelles)
    for section, values in content.items():
        if section not in existing_data:
            existing_data[section] = {}
        existing_data[section].update(values)
    
    # Sauvegarde du fichier enrichi
    save_json(file_path, existing_data)
    print(f"Fichier {file_path} enrichi avec succès")

print("\nEnrichissement terminé pour la section 'jobs'.")
