#!/usr/bin/env python3
import json
import os
import glob
import shutil

# Fonction pour charger un fichier JSON existant
def load_json(file_path):
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return {}

# Fonction pour sauvegarder un fichier JSON
def save_json(file_path, data):
    os.makedirs(os.path.dirname(file_path), exist_ok=True)
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

# Structure des traductions pour la section "search"
search_translations = {
    "en": {
        "search": {
            "searchJobs": "Search jobs",
            "keywords": "Keywords",
            "location": "Location",
            "category": "Category",
            "jobType": "Job type",
            "salary": "Salary",
            "experience": "Experience",
            "filters": "Filters",
            "sortBy": "Sort by",
            "relevance": "Relevance",
            "datePosted": "Date posted",
            "remote": "Remote",
            "onSite": "On-site",
            "hybrid": "Hybrid",
            "fullTime": "Full-time",
            "partTime": "Part-time",
            "contract": "Contract",
            "temporary": "Temporary",
            "internship": "Internship",
            "entrylevel": "Entry level",
            "midLevel": "Mid level",
            "seniorLevel": "Senior level",
            "executive": "Executive",
            "searchResults": "Search results",
            "noResults": "No results found",
            "tryDifferentKeywords": "Try different keywords or filters",
            "clearAllFilters": "Clear all filters",
            "applyFilters": "Apply filters",
            "anyLocation": "Any location",
            "anyCategory": "Any category",
            "anyJobType": "Any job type",
            "anySalary": "Any salary",
            "anyExperience": "Any experience",
            "jobsFound": "jobs found",
            "similarJobs": "Similar jobs",
            "featuredJobs": "Featured jobs",
            "popularSearches": "Popular searches",
            "recentSearches": "Recent searches",
            "saveSearch": "Save search",
            "savedSearches": "Saved searches",
            "jobAlerts": "Job alerts",
            "distanceFrom": "Distance from",
            "within": "Within",
            "km": "km",
            "miles": "miles",
            "hourly": "Hourly",
            "monthly": "Monthly",
            "yearly": "Yearly",
            "minimumSalary": "Minimum salary",
            "maximumSalary": "Maximum salary",
            "postedToday": "Posted today",
            "postedThisWeek": "Posted this week",
            "postedThisMonth": "Posted this month",
            "companySize": "Company size",
            "small": "Small (1-50 employees)",
            "medium": "Medium (51-200 employees)",
            "large": "Large (201-1000 employees)",
            "enterprise": "Enterprise (1000+ employees)"
        }
    },
    "fr": {
        "search": {
            "searchJobs": "Rechercher des emplois",
            "keywords": "Mots-clés",
            "location": "Localisation",
            "category": "Catégorie",
            "jobType": "Type d'emploi",
            "salary": "Salaire",
            "experience": "Expérience",
            "filters": "Filtres",
            "sortBy": "Trier par",
            "relevance": "Pertinence",
            "datePosted": "Date de publication",
            "remote": "Télétravail",
            "onSite": "Sur site",
            "hybrid": "Hybride",
            "fullTime": "Temps plein",
            "partTime": "Temps partiel",
            "contract": "Contrat",
            "temporary": "Temporaire",
            "internship": "Stage",
            "entrylevel": "Débutant",
            "midLevel": "Confirmé",
            "seniorLevel": "Senior",
            "executive": "Cadre supérieur",
            "searchResults": "Résultats de recherche",
            "noResults": "Aucun résultat trouvé",
            "tryDifferentKeywords": "Essayez d'autres mots-clés ou filtres",
            "clearAllFilters": "Effacer tous les filtres",
            "applyFilters": "Appliquer les filtres",
            "anyLocation": "N'importe où",
            "anyCategory": "Toutes catégories",
            "anyJobType": "Tous types d'emploi",
            "anySalary": "Tous salaires",
            "anyExperience": "Toute expérience",
            "jobsFound": "emplois trouvés",
            "similarJobs": "Emplois similaires",
            "featuredJobs": "Emplois en vedette",
            "popularSearches": "Recherches populaires",
            "recentSearches": "Recherches récentes",
            "saveSearch": "Sauvegarder la recherche",
            "savedSearches": "Recherches sauvegardées",
            "jobAlerts": "Alertes emploi",
            "distanceFrom": "Distance de",
            "within": "Dans un rayon de",
            "km": "km",
            "miles": "miles",
            "hourly": "Horaire",
            "monthly": "Mensuel",
            "yearly": "Annuel",
            "minimumSalary": "Salaire minimum",
            "maximumSalary": "Salaire maximum",
            "postedToday": "Publié aujourd'hui",
            "postedThisWeek": "Publié cette semaine",
            "postedThisMonth": "Publié ce mois-ci",
            "companySize": "Taille de l'entreprise",
            "small": "Petite (1-50 employés)",
            "medium": "Moyenne (51-200 employés)",
            "large": "Grande (201-1000 employés)",
            "enterprise": "Très grande (1000+ employés)"
        }
    },
    "de": {
        "search": {
            "searchJobs": "Jobs suchen",
            "keywords": "Suchbegriffe",
            "location": "Standort",
            "category": "Kategorie",
            "jobType": "Beschäftigungsart",
            "salary": "Gehalt",
            "experience": "Erfahrung",
            "filters": "Filter",
            "sortBy": "Sortieren nach",
            "relevance": "Relevanz",
            "datePosted": "Veröffentlichungsdatum",
            "remote": "Remote",
            "onSite": "Vor Ort",
            "hybrid": "Hybrid",
            "fullTime": "Vollzeit",
            "partTime": "Teilzeit",
            "contract": "Befristet",
            "temporary": "Temporär",
            "internship": "Praktikum",
            "entrylevel": "Einstiegslevel",
            "midLevel": "Mittlere Ebene",
            "seniorLevel": "Senior-Level",
            "executive": "Führungsposition",
            "searchResults": "Suchergebnisse",
            "noResults": "Keine Ergebnisse gefunden",
            "tryDifferentKeywords": "Versuchen Sie andere Suchbegriffe oder Filter",
            "clearAllFilters": "Alle Filter löschen",
            "applyFilters": "Filter anwenden",
            "anyLocation": "Beliebiger Standort",
            "anyCategory": "Beliebige Kategorie",
            "anyJobType": "Beliebige Beschäftigungsart",
            "anySalary": "Beliebiges Gehalt",
            "anyExperience": "Beliebige Erfahrung",
            "jobsFound": "Jobs gefunden",
            "similarJobs": "Ähnliche Jobs",
            "featuredJobs": "Empfohlene Jobs",
            "popularSearches": "Beliebte Suchanfragen",
            "recentSearches": "Neueste Suchanfragen",
            "saveSearch": "Suche speichern",
            "savedSearches": "Gespeicherte Suchen",
            "jobAlerts": "Job-Benachrichtigungen",
            "distanceFrom": "Entfernung von",
            "within": "Innerhalb von",
            "km": "km",
            "miles": "Meilen",
            "hourly": "Stündlich",
            "monthly": "Monatlich",
            "yearly": "Jährlich",
            "minimumSalary": "Mindestgehalt",
            "maximumSalary": "Maximalgehalt",
            "postedToday": "Heute veröffentlicht",
            "postedThisWeek": "Diese Woche veröffentlicht",
            "postedThisMonth": "Diesen Monat veröffentlicht",
            "companySize": "Unternehmensgröße",
            "small": "Klein (1-50 Mitarbeiter)",
            "medium": "Mittel (51-200 Mitarbeiter)",
            "large": "Groß (201-1000 Mitarbeiter)",
            "enterprise": "Sehr groß (1000+ Mitarbeiter)"
        }
    },
    "es": {
        "search": {
            "searchJobs": "Buscar empleos",
            "keywords": "Palabras clave",
            "location": "Ubicación",
            "category": "Categoría",
            "jobType": "Tipo de empleo",
            "salary": "Salario",
            "experience": "Experiencia",
            "filters": "Filtros",
            "sortBy": "Ordenar por",
            "relevance": "Relevancia",
            "datePosted": "Fecha de publicación",
            "remote": "En remoto",
            "onSite": "Presencial",
            "hybrid": "Híbrido",
            "fullTime": "Tiempo completo",
            "partTime": "Tiempo parcial",
            "contract": "Contrato",
            "temporary": "Temporal",
            "internship": "Prácticas",
            "entrylevel": "Nivel inicial",
            "midLevel": "Nivel medio",
            "seniorLevel": "Nivel senior",
            "executive": "Ejecutivo",
            "searchResults": "Resultados de búsqueda",
            "noResults": "No se encontraron resultados",
            "tryDifferentKeywords": "Pruebe con otras palabras clave o filtros",
            "clearAllFilters": "Borrar todos los filtros",
            "applyFilters": "Aplicar filtros",
            "anyLocation": "Cualquier ubicación",
            "anyCategory": "Cualquier categoría",
            "anyJobType": "Cualquier tipo de empleo",
            "anySalary": "Cualquier salario",
            "anyExperience": "Cualquier experiencia",
            "jobsFound": "empleos encontrados",
            "similarJobs": "Empleos similares",
            "featuredJobs": "Empleos destacados",
            "popularSearches": "Búsquedas populares",
            "recentSearches": "Búsquedas recientes",
            "saveSearch": "Guardar búsqueda",
            "savedSearches": "Búsquedas guardadas",
            "jobAlerts": "Alertas de empleo",
            "distanceFrom": "Distancia desde",
            "within": "Dentro de",
            "km": "km",
            "miles": "millas",
            "hourly": "Por hora",
            "monthly": "Mensual",
            "yearly": "Anual",
            "minimumSalary": "Salario mínimo",
            "maximumSalary": "Salario máximo",
            "postedToday": "Publicado hoy",
            "postedThisWeek": "Publicado esta semana",
            "postedThisMonth": "Publicado este mes",
            "companySize": "Tamaño de la empresa",
            "small": "Pequeña (1-50 empleados)",
            "medium": "Mediana (51-200 empleados)",
            "large": "Grande (201-1000 empleados)",
            "enterprise": "Muy grande (1000+ empleados)"
        }
    },
    "it": {
        "search": {
            "searchJobs": "Cerca lavori",
            "keywords": "Parole chiave",
            "location": "Località",
            "category": "Categoria",
            "jobType": "Tipo di lavoro",
            "salary": "Stipendio",
            "experience": "Esperienza",
            "filters": "Filtri",
            "sortBy": "Ordina per",
            "relevance": "Rilevanza",
            "datePosted": "Data di pubblicazione",
            "remote": "Da remoto",
            "onSite": "In sede",
            "hybrid": "Ibrido",
            "fullTime": "Tempo pieno",
            "partTime": "Part-time",
            "contract": "Contratto",
            "temporary": "Temporaneo",
            "internship": "Stage",
            "entrylevel": "Livello base",
            "midLevel": "Livello intermedio",
            "seniorLevel": "Livello senior",
            "executive": "Dirigente",
            "searchResults": "Risultati della ricerca",
            "noResults": "Nessun risultato trovato",
            "tryDifferentKeywords": "Prova parole chiave o filtri diversi",
            "clearAllFilters": "Cancella tutti i filtri",
            "applyFilters": "Applica filtri",
            "anyLocation": "Qualsiasi località",
            "anyCategory": "Qualsiasi categoria",
            "anyJobType": "Qualsiasi tipo di lavoro",
            "anySalary": "Qualsiasi stipendio",
            "anyExperience": "Qualsiasi esperienza",
            "jobsFound": "lavori trovati",
            "similarJobs": "Lavori simili",
            "featuredJobs": "Lavori in evidenza",
            "popularSearches": "Ricerche popolari",
            "recentSearches": "Ricerche recenti",
            "saveSearch": "Salva ricerca",
            "savedSearches": "Ricerche salvate",
            "jobAlerts": "Avvisi di lavoro",
            "distanceFrom": "Distanza da",
            "within": "Entro",
            "km": "km",
            "miles": "miglia",
            "hourly": "Orario",
            "monthly": "Mensile",
            "yearly": "Annuale",
            "minimumSalary": "Stipendio minimo",
            "maximumSalary": "Stipendio massimo",
            "postedToday": "Pubblicato oggi",
            "postedThisWeek": "Pubblicato questa settimana",
            "postedThisMonth": "Pubblicato questo mese",
            "companySize": "Dimensione dell'azienda",
            "small": "Piccola (1-50 dipendenti)",
            "medium": "Media (51-200 dipendenti)",
            "large": "Grande (201-1000 dipendenti)",
            "enterprise": "Molto grande (1000+ dipendenti)"
        }
    }
}

# Enrichir les fichiers existants
print("Enrichissement des fichiers de traduction pour la section 'search'...")
for lang, content in search_translations.items():
    file_path = f"public/locales/{lang}/common.json"
    existing_data = load_json(file_path)
    
    # Fusion des données (priorité aux nouvelles)
    for section, values in content.items():
        if section not in existing_data:
            existing_data[section] = {}
        existing_data[section].update(values)
    
    # Sauvegarde du fichier enrichi
    save_json(file_path, existing_data)
    print(f"Fichier {file_path} enrichi avec succès")

print("\nEnrichissement terminé pour la section 'search'.")
