#!/usr/bin/env python3
import json
import os
import glob
import shutil

# Fonction pour charger un fichier JSON existant
def load_json(file_path):
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return {}

# Fonction pour sauvegarder un fichier JSON
def save_json(file_path, data):
    os.makedirs(os.path.dirname(file_path), exist_ok=True)
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

# Structure des traductions pour la section "forms"
forms_translations = {
    "en": {
        "forms": {
            "required": "Required",
            "optional": "Optional",
            "submit": "Submit",
            "cancel": "Cancel",
            "error": "Error",
            "success": "Success",
            "loading": "Loading",
            "firstName": "First name",
            "lastName": "Last name",
            "email": "Email address",
            "phone": "Phone number",
            "address": "Address",
            "city": "City",
            "state": "State/Province",
            "zipCode": "Zip/Postal code",
            "country": "Country",
            "dateOfBirth": "Date of birth",
            "education": "Education",
            "university": "University",
            "degree": "Degree",
            "major": "Major",
            "graduationDate": "Graduation date",
            "workExperience": "Work experience",
            "company": "Company",
            "position": "Position",
            "startDate": "Start date",
            "endDate": "End date",
            "current": "Current",
            "description": "Description",
            "skills": "Skills",
            "languages": "Languages",
            "upload": "Upload",
            "dragAndDrop": "Drag and drop or click to upload",
            "fileTypes": "Supported file types",
            "maxFileSize": "Maximum file size",
            "fieldRequired": "This field is required",
            "invalidEmail": "Please enter a valid email address",
            "invalidPhone": "Please enter a valid phone number",
            "invalidDate": "Please enter a valid date",
            "invalidUrl": "Please enter a valid URL",
            "invalidFileType": "Invalid file type",
            "fileTooLarge": "File is too large",
            "pleaseSelect": "Please select an option",
            "selectDate": "Select date",
            "addMore": "Add more",
            "remove": "Remove",
            "save": "Save",
            "saveAndContinue": "Save and continue",
            "previous": "Previous",
            "next": "Next",
            "fillAllFields": "Please fill all required fields",
            "reviewBeforeSubmit": "Please review before submitting",
            "changesSaved": "Changes saved successfully",
            "errorSaving": "Error saving changes",
            "formSubmitted": "Form submitted successfully",
            "errorSubmitting": "Error submitting form",
            "goBack": "Go back",
            "tryAgain": "Try again",
            "formNotComplete": "Form is not complete",
            "errorMessage": "An error occurred. Please try again."
        }
    },
    "fr": {
        "forms": {
            "required": "Obligatoire",
            "optional": "Facultatif",
            "submit": "Soumettre",
            "cancel": "Annuler",
            "error": "Erreur",
            "success": "Succès",
            "loading": "Chargement",
            "firstName": "Prénom",
            "lastName": "Nom",
            "email": "Adresse e-mail",
            "phone": "Numéro de téléphone",
            "address": "Adresse",
            "city": "Ville",
            "state": "État/Province",
            "zipCode": "Code postal",
            "country": "Pays",
            "dateOfBirth": "Date de naissance",
            "education": "Formation",
            "university": "Université",
            "degree": "Diplôme",
            "major": "Spécialisation",
            "graduationDate": "Date d'obtention",
            "workExperience": "Expérience professionnelle",
            "company": "Entreprise",
            "position": "Poste",
            "startDate": "Date de début",
            "endDate": "Date de fin",
            "current": "Actuel",
            "description": "Description",
            "skills": "Compétences",
            "languages": "Langues",
            "upload": "Télécharger",
            "dragAndDrop": "Glisser-déposer ou cliquer pour télécharger",
            "fileTypes": "Types de fichiers pris en charge",
            "maxFileSize": "Taille maximale de fichier",
            "fieldRequired": "Ce champ est obligatoire",
            "invalidEmail": "Veuillez saisir une adresse e-mail valide",
            "invalidPhone": "Veuillez saisir un numéro de téléphone valide",
            "invalidDate": "Veuillez saisir une date valide",
            "invalidUrl": "Veuillez saisir une URL valide",
            "invalidFileType": "Type de fichier non valide",
            "fileTooLarge": "Le fichier est trop volumineux",
            "pleaseSelect": "Veuillez sélectionner une option",
            "selectDate": "Sélectionner une date",
            "addMore": "Ajouter plus",
            "remove": "Supprimer",
            "save": "Enregistrer",
            "saveAndContinue": "Enregistrer et continuer",
            "previous": "Précédent",
            "next": "Suivant",
            "fillAllFields": "Veuillez remplir tous les champs obligatoires",
            "reviewBeforeSubmit": "Veuillez vérifier avant de soumettre",
            "changesSaved": "Modifications enregistrées avec succès",
            "errorSaving": "Erreur lors de l'enregistrement des modifications",
            "formSubmitted": "Formulaire soumis avec succès",
            "errorSubmitting": "Erreur lors de la soumission du formulaire",
            "goBack": "Retour",
            "tryAgain": "Réessayer",
            "formNotComplete": "Le formulaire n'est pas complet",
            "errorMessage": "Une erreur s'est produite. Veuillez réessayer."
        }
    },
    "de": {
        "forms": {
            "required": "Erforderlich",
            "optional": "Optional",
            "submit": "Absenden",
            "cancel": "Abbrechen",
            "error": "Fehler",
            "success": "Erfolg",
            "loading": "Laden",
            "firstName": "Vorname",
            "lastName": "Nachname",
            "email": "E-Mail-Adresse",
            "phone": "Telefonnummer",
            "address": "Adresse",
            "city": "Stadt",
            "state": "Bundesland/Provinz",
            "zipCode": "Postleitzahl",
            "country": "Land",
            "dateOfBirth": "Geburtsdatum",
            "education": "Bildung",
            "university": "Universität",
            "degree": "Abschluss",
            "major": "Hauptfach",
            "graduationDate": "Abschlussdatum",
            "workExperience": "Berufserfahrung",
            "company": "Unternehmen",
            "position": "Position",
            "startDate": "Startdatum",
            "endDate": "Enddatum",
            "current": "Aktuell",
            "description": "Beschreibung",
            "skills": "Fähigkeiten",
            "languages": "Sprachen",
            "upload": "Hochladen",
            "dragAndDrop": "Ziehen und ablegen oder klicken zum Hochladen",
            "fileTypes": "Unterstützte Dateitypen",
            "maxFileSize": "Maximale Dateigröße",
            "fieldRequired": "Dieses Feld ist erforderlich",
            "invalidEmail": "Bitte geben Sie eine gültige E-Mail-Adresse ein",
            "invalidPhone": "Bitte geben Sie eine gültige Telefonnummer ein",
            "invalidDate": "Bitte geben Sie ein gültiges Datum ein",
            "invalidUrl": "Bitte geben Sie eine gültige URL ein",
            "invalidFileType": "Ungültiger Dateityp",
            "fileTooLarge": "Datei ist zu groß",
            "pleaseSelect": "Bitte wählen Sie eine Option",
            "selectDate": "Datum auswählen",
            "addMore": "Mehr hinzufügen",
            "remove": "Entfernen",
            "save": "Speichern",
            "saveAndContinue": "Speichern und fortfahren",
            "previous": "Zurück",
            "next": "Weiter",
            "fillAllFields": "Bitte füllen Sie alle erforderlichen Felder aus",
            "reviewBeforeSubmit": "Bitte überprüfen Sie vor dem Absenden",
            "changesSaved": "Änderungen erfolgreich gespeichert",
            "errorSaving": "Fehler beim Speichern der Änderungen",
            "formSubmitted": "Formular erfolgreich abgesendet",
            "errorSubmitting": "Fehler beim Absenden des Formulars",
            "goBack": "Zurück",
            "tryAgain": "Erneut versuchen",
            "formNotComplete": "Formular ist nicht vollständig",
            "errorMessage": "Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut."
        }
    },
    "es": {
        "forms": {
            "required": "Obligatorio",
            "optional": "Opcional",
            "submit": "Enviar",
            "cancel": "Cancelar",
            "error": "Error",
            "success": "Éxito",
            "loading": "Cargando",
            "firstName": "Nombre",
            "lastName": "Apellido",
            "email": "Correo electrónico",
            "phone": "Número de teléfono",
            "address": "Dirección",
            "city": "Ciudad",
            "state": "Estado/Provincia",
            "zipCode": "Código postal",
            "country": "País",
            "dateOfBirth": "Fecha de nacimiento",
            "education": "Educación",
            "university": "Universidad",
            "degree": "Título",
            "major": "Especialidad",
            "graduationDate": "Fecha de graduación",
            "workExperience": "Experiencia laboral",
            "company": "Empresa",
            "position": "Puesto",
            "startDate": "Fecha de inicio",
            "endDate": "Fecha de finalización",
            "current": "Actual",
            "description": "Descripción",
            "skills": "Habilidades",
            "languages": "Idiomas",
            "upload": "Subir",
            "dragAndDrop": "Arrastrar y soltar o hacer clic para subir",
            "fileTypes": "Tipos de archivo compatibles",
            "maxFileSize": "Tamaño máximo de archivo",
            "fieldRequired": "Este campo es obligatorio",
            "invalidEmail": "Por favor, introduce un correo electrónico válido",
            "invalidPhone": "Por favor, introduce un número de teléfono válido",
            "invalidDate": "Por favor, introduce una fecha válida",
            "invalidUrl": "Por favor, introduce una URL válida",
            "invalidFileType": "Tipo de archivo no válido",
            "fileTooLarge": "El archivo es demasiado grande",
            "pleaseSelect": "Por favor, selecciona una opción",
            "selectDate": "Seleccionar fecha",
            "addMore": "Añadir más",
            "remove": "Eliminar",
            "save": "Guardar",
            "saveAndContinue": "Guardar y continuar",
            "previous": "Anterior",
            "next": "Siguiente",
            "fillAllFields": "Por favor, rellena todos los campos obligatorios",
            "reviewBeforeSubmit": "Por favor, revisa antes de enviar",
            "changesSaved": "Cambios guardados correctamente",
            "errorSaving": "Error al guardar los cambios",
            "formSubmitted": "Formulario enviado correctamente",
            "errorSubmitting": "Error al enviar el formulario",
            "goBack": "Volver",
            "tryAgain": "Intentar de nuevo",
            "formNotComplete": "El formulario no está completo",
            "errorMessage": "Ha ocurrido un error. Por favor, inténtalo de nuevo."
        }
    },
    "it": {
        "forms": {
            "required": "Obbligatorio",
            "optional": "Facoltativo",
            "submit": "Invia",
            "cancel": "Annulla",
            "error": "Errore",
            "success": "Successo",
            "loading": "Caricamento",
            "firstName": "Nome",
            "lastName": "Cognome",
            "email": "Indirizzo email",
            "phone": "Numero di telefono",
            "address": "Indirizzo",
            "city": "Città",
            "state": "Stato/Provincia",
            "zipCode": "CAP",
            "country": "Paese",
            "dateOfBirth": "Data di nascita",
            "education": "Istruzione",
            "university": "Università",
            "degree": "Titolo di studio",
            "major": "Specializzazione",
            "graduationDate": "Data di laurea",
            "workExperience": "Esperienza lavorativa",
            "company": "Azienda",
            "position": "Posizione",
            "startDate": "Data di inizio",
            "endDate": "Data di fine",
            "current": "Attuale",
            "description": "Descrizione",
            "skills": "Competenze",
            "languages": "Lingue",
            "upload": "Carica",
            "dragAndDrop": "Trascina e rilascia o clicca per caricare",
            "fileTypes": "Tipi di file supportati",
            "maxFileSize": "Dimensione massima del file",
            "fieldRequired": "Questo campo è obbligatorio",
            "invalidEmail": "Inserisci un indirizzo email valido",
            "invalidPhone": "Inserisci un numero di telefono valido",
            "invalidDate": "Inserisci una data valida",
            "invalidUrl": "Inserisci un URL valido",
            "invalidFileType": "Tipo di file non valido",
            "fileTooLarge": "Il file è troppo grande",
            "pleaseSelect": "Seleziona un'opzione",
            "selectDate": "Seleziona data",
            "addMore": "Aggiungi altro",
            "remove": "Rimuovi",
            "save": "Salva",
            "saveAndContinue": "Salva e continua",
            "previous": "Precedente",
            "next": "Successivo",
            "fillAllFields": "Compila tutti i campi obbligatori",
            "reviewBeforeSubmit": "Rivedi prima di inviare",
            "changesSaved": "Modifiche salvate con successo",
            "errorSaving": "Errore durante il salvataggio delle modifiche",
            "formSubmitted": "Modulo inviato con successo",
            "errorSubmitting": "Errore durante l'invio del modulo",
            "goBack": "Torna indietro",
            "tryAgain": "Riprova",
            "formNotComplete": "Il modulo non è completo",
            "errorMessage": "Si è verificato un errore. Riprova."
        }
    }
}

# Enrichir les fichiers existants
print("Enrichissement des fichiers de traduction pour la section 'forms'...")
for lang, content in forms_translations.items():
    file_path = f"public/locales/{lang}/common.json"
    existing_data = load_json(file_path)
    
    # Fusion des données (priorité aux nouvelles)
    for section, values in content.items():
        if section not in existing_data:
            existing_data[section] = {}
        existing_data[section].update(values)
    
    # Sauvegarde du fichier enrichi
    save_json(file_path, existing_data)
    print(f"Fichier {file_path} enrichi avec succès")

print("\nEnrichissement terminé pour la section 'forms'.")
