#!/usr/bin/env python3
import json
import os
import glob
import shutil

# Fonction pour charger un fichier JSON existant
def load_json(file_path):
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return {}

# Fonction pour sauvegarder un fichier JSON
def save_json(file_path, data):
    os.makedirs(os.path.dirname(file_path), exist_ok=True)
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

# Structure des traductions pour la section "profile"
profile_translations = {
    "en": {
        "profile": {
            "title": "Profile",
            "editProfile": "Edit Profile",
            "personalInfo": "Personal Information",
            "professionalInfo": "Professional Information",
            "contactInfo": "Contact Information",
            "about": "About Me",
            "experience": "Experience",
            "education": "Education",
            "skills": "Skills",
            "languages": "Languages",
            "certifications": "Certifications",
            "projects": "Projects",
            "publications": "Publications",
            "awards": "Awards",
            "recommendations": "Recommendations",
            "profileVisibility": "Profile Visibility",
            "public": "Public",
            "private": "Private",
            "connections": "Connections",
            "saveChanges": "Save Changes",
            "discardChanges": "Discard Changes",
            "profilePicture": "Profile Picture",
            "changePicture": "Change Picture",
            "removePicture": "Remove Picture",
            "uploadNew": "Upload New",
            "firstName": "First Name",
            "lastName": "Last Name",
            "headline": "Headline",
            "summary": "Summary",
            "location": "Location",
            "industry": "Industry",
            "website": "Website",
            "birthday": "Birthday",
            "phone": "Phone",
            "email": "Email",
            "address": "Address",
            "socialProfiles": "Social Profiles",
            "addExperience": "Add Experience",
            "addEducation": "Add Education",
            "addSkill": "Add Skill",
            "addLanguage": "Add Language",
            "addCertification": "Add Certification",
            "addProject": "Add Project",
            "company": "Company",
            "position": "Position",
            "startDate": "Start Date",
            "endDate": "End Date",
            "current": "Current",
            "description": "Description",
            "school": "School",
            "degree": "Degree",
            "fieldOfStudy": "Field of Study",
            "grade": "Grade",
            "activities": "Activities",
            "proficiency": "Proficiency",
            "beginner": "Beginner",
            "intermediate": "Intermediate",
            "advanced": "Advanced",
            "fluent": "Fluent",
            "native": "Native",
            "credentialID": "Credential ID",
            "issuingOrganization": "Issuing Organization",
            "issueDate": "Issue Date",
            "expirationDate": "Expiration Date",
            "noExpiration": "No Expiration",
            "projectName": "Project Name",
            "projectURL": "Project URL",
            "profilePreview": "Profile Preview",
            "profileStrength": "Profile Strength",
            "profileCompletion": "Profile Completion",
            "basicInfo": "Basic Information",
            "viewAs": "View As",
            "publicProfile": "Public Profile",
            "urlSlug": "URL Slug",
            "customURL": "Custom URL"
        }
    },
    "fr": {
        "profile": {
            "title": "Profil",
            "editProfile": "Modifier le profil",
            "personalInfo": "Informations personnelles",
            "professionalInfo": "Informations professionnelles",
            "contactInfo": "Coordonnées",
            "about": "À propos de moi",
            "experience": "Expérience",
            "education": "Formation",
            "skills": "Compétences",
            "languages": "Langues",
            "certifications": "Certifications",
            "projects": "Projets",
            "publications": "Publications",
            "awards": "Récompenses",
            "recommendations": "Recommandations",
            "profileVisibility": "Visibilité du profil",
            "public": "Public",
            "private": "Privé",
            "connections": "Connexions",
            "saveChanges": "Enregistrer les modifications",
            "discardChanges": "Annuler les modifications",
            "profilePicture": "Photo de profil",
            "changePicture": "Changer la photo",
            "removePicture": "Supprimer la photo",
            "uploadNew": "Télécharger une nouvelle",
            "firstName": "Prénom",
            "lastName": "Nom",
            "headline": "Titre",
            "summary": "Résumé",
            "location": "Lieu",
            "industry": "Secteur",
            "website": "Site web",
            "birthday": "Date de naissance",
            "phone": "Téléphone",
            "email": "E-mail",
            "address": "Adresse",
            "socialProfiles": "Profils sociaux",
            "addExperience": "Ajouter une expérience",
            "addEducation": "Ajouter une formation",
            "addSkill": "Ajouter une compétence",
            "addLanguage": "Ajouter une langue",
            "addCertification": "Ajouter une certification",
            "addProject": "Ajouter un projet",
            "company": "Entreprise",
            "position": "Poste",
            "startDate": "Date de début",
            "endDate": "Date de fin",
            "current": "Actuel",
            "description": "Description",
            "school": "École",
            "degree": "Diplôme",
            "fieldOfStudy": "Domaine d'études",
            "grade": "Mention",
            "activities": "Activités",
            "proficiency": "Niveau",
            "beginner": "Débutant",
            "intermediate": "Intermédiaire",
            "advanced": "Avancé",
            "fluent": "Courant",
            "native": "Langue maternelle",
            "credentialID": "Identifiant de certification",
            "issuingOrganization": "Organisation émettrice",
            "issueDate": "Date d'émission",
            "expirationDate": "Date d'expiration",
            "noExpiration": "Sans expiration",
            "projectName": "Nom du projet",
            "projectURL": "URL du projet",
            "profilePreview": "Aperçu du profil",
            "profileStrength": "Force du profil",
            "profileCompletion": "Complétude du profil",
            "basicInfo": "Informations de base",
            "viewAs": "Voir comme",
            "publicProfile": "Profil public",
            "urlSlug": "Slug URL",
            "customURL": "URL personnalisée"
        }
    },
    "de": {
        "profile": {
            "title": "Profil",
            "editProfile": "Profil bearbeiten",
            "personalInfo": "Persönliche Informationen",
            "professionalInfo": "Berufliche Informationen",
            "contactInfo": "Kontaktinformationen",
            "about": "Über mich",
            "experience": "Erfahrung",
            "education": "Bildung",
            "skills": "Fähigkeiten",
            "languages": "Sprachen",
            "certifications": "Zertifizierungen",
            "projects": "Projekte",
            "publications": "Publikationen",
            "awards": "Auszeichnungen",
            "recommendations": "Empfehlungen",
            "profileVisibility": "Profilsichtbarkeit",
            "public": "Öffentlich",
            "private": "Privat",
            "connections": "Verbindungen",
            "saveChanges": "Änderungen speichern",
            "discardChanges": "Änderungen verwerfen",
            "profilePicture": "Profilbild",
            "changePicture": "Bild ändern",
            "removePicture": "Bild entfernen",
            "uploadNew": "Neues hochladen",
            "firstName": "Vorname",
            "lastName": "Nachname",
            "headline": "Überschrift",
            "summary": "Zusammenfassung",
            "location": "Standort",
            "industry": "Branche",
            "website": "Webseite",
            "birthday": "Geburtstag",
            "phone": "Telefon",
            "email": "E-Mail",
            "address": "Adresse",
            "socialProfiles": "Soziale Profile",
            "addExperience": "Erfahrung hinzufügen",
            "addEducation": "Bildung hinzufügen",
            "addSkill": "Fähigkeit hinzufügen",
            "addLanguage": "Sprache hinzufügen",
            "addCertification": "Zertifizierung hinzufügen",
            "addProject": "Projekt hinzufügen",
            "company": "Unternehmen",
            "position": "Position",
            "startDate": "Startdatum",
            "endDate": "Enddatum",
            "current": "Aktuell",
            "description": "Beschreibung",
            "school": "Schule",
            "degree": "Abschluss",
            "fieldOfStudy": "Studienbereich",
            "grade": "Note",
            "activities": "Aktivitäten",
            "proficiency": "Kenntnisstand",
            "beginner": "Anfänger",
            "intermediate": "Mittelstufe",
            "advanced": "Fortgeschritten",
            "fluent": "Fließend",
            "native": "Muttersprache",
            "credentialID": "Anmeldedaten-ID",
            "issuingOrganization": "Ausstellende Organisation",
            "issueDate": "Ausstellungsdatum",
            "expirationDate": "Ablaufdatum",
            "noExpiration": "Kein Ablauf",
            "projectName": "Projektname",
            "projectURL": "Projekt-URL",
            "profilePreview": "Profilvorschau",
            "profileStrength": "Profilstärke",
            "profileCompletion": "Profilvollständigkeit",
            "basicInfo": "Grundlegende Informationen",
            "viewAs": "Ansehen als",
            "publicProfile": "Öffentliches Profil",
            "urlSlug": "URL-Slug",
            "customURL": "Benutzerdefinierte URL"
        }
    },
    "es": {
        "profile": {
            "title": "Perfil",
            "editProfile": "Editar perfil",
            "personalInfo": "Información personal",
            "professionalInfo": "Información profesional",
            "contactInfo": "Información de contacto",
            "about": "Sobre mí",
            "experience": "Experiencia",
            "education": "Educación",
            "skills": "Habilidades",
            "languages": "Idiomas",
            "certifications": "Certificaciones",
            "projects": "Proyectos",
            "publications": "Publicaciones",
            "awards": "Premios",
            "recommendations": "Recomendaciones",
            "profileVisibility": "Visibilidad del perfil",
            "public": "Público",
            "private": "Privado",
            "connections": "Conexiones",
            "saveChanges": "Guardar cambios",
            "discardChanges": "Descartar cambios",
            "profilePicture": "Foto de perfil",
            "changePicture": "Cambiar foto",
            "removePicture": "Eliminar foto",
            "uploadNew": "Subir nueva",
            "firstName": "Nombre",
            "lastName": "Apellido",
            "headline": "Titular",
            "summary": "Resumen",
            "location": "Ubicación",
            "industry": "Industria",
            "website": "Sitio web",
            "birthday": "Fecha de nacimiento",
            "phone": "Teléfono",
            "email": "Correo electrónico",
            "address": "Dirección",
            "socialProfiles": "Perfiles sociales",
            "addExperience": "Añadir experiencia",
            "addEducation": "Añadir educación",
            "addSkill": "Añadir habilidad",
            "addLanguage": "Añadir idioma",
            "addCertification": "Añadir certificación",
            "addProject": "Añadir proyecto",
            "company": "Empresa",
            "position": "Puesto",
            "startDate": "Fecha de inicio",
            "endDate": "Fecha de finalización",
            "current": "Actual",
            "description": "Descripción",
            "school": "Centro educativo",
            "degree": "Título",
            "fieldOfStudy": "Campo de estudio",
            "grade": "Calificación",
            "activities": "Actividades",
            "proficiency": "Nivel",
            "beginner": "Principiante",
            "intermediate": "Intermedio",
            "advanced": "Avanzado",
            "fluent": "Fluido",
            "native": "Nativo",
            "credentialID": "ID de credencial",
            "issuingOrganization": "Organización emisora",
            "issueDate": "Fecha de emisión",
            "expirationDate": "Fecha de vencimiento",
            "noExpiration": "Sin vencimiento",
            "projectName": "Nombre del proyecto",
            "projectURL": "URL del proyecto",
            "profilePreview": "Vista previa del perfil",
            "profileStrength": "Fortaleza del perfil",
            "profileCompletion": "Completitud del perfil",
            "basicInfo": "Información básica",
            "viewAs": "Ver como",
            "publicProfile": "Perfil público",
            "urlSlug": "Slug URL",
            "customURL": "URL personalizada"
        }
    },
    "it": {
        "profile": {
            "title": "Profilo",
            "editProfile": "Modifica profilo",
            "personalInfo": "Informazioni personali",
            "professionalInfo": "Informazioni professionali",
            "contactInfo": "Informazioni di contatto",
            "about": "Su di me",
            "experience": "Esperienza",
            "education": "Istruzione",
            "skills": "Competenze",
            "languages": "Lingue",
            "certifications": "Certificazioni",
            "projects": "Progetti",
            "publications": "Pubblicazioni",
            "awards": "Riconoscimenti",
            "recommendations": "Raccomandazioni",
            "profileVisibility": "Visibilità del profilo",
            "public": "Pubblico",
            "private": "Privato",
            "connections": "Connessioni",
            "saveChanges": "Salva modifiche",
            "discardChanges": "Annulla modifiche",
            "profilePicture": "Foto del profilo",
            "changePicture": "Cambia foto",
            "removePicture": "Rimuovi foto",
            "uploadNew": "Carica nuova",
            "firstName": "Nome",
            "lastName": "Cognome",
            "headline": "Titolo",
            "summary": "Riepilogo",
            "location": "Località",
            "industry": "Settore",
            "website": "Sito web",
            "birthday": "Data di nascita",
            "phone": "Telefono",
            "email": "Email",
            "address": "Indirizzo",
            "socialProfiles": "Profili social",
            "addExperience": "Aggiungi esperienza",
            "addEducation": "Aggiungi istruzione",
            "addSkill": "Aggiungi competenza",
            "addLanguage": "Aggiungi lingua",
            "addCertification": "Aggiungi certificazione",
            "addProject": "Aggiungi progetto",
            "company": "Azienda",
            "position": "Posizione",
            "startDate": "Data di inizio",
            "endDate": "Data di fine",
            "current": "Attuale",
            "description": "Descrizione",
            "school": "Scuola",
            "degree": "Titolo di studio",
            "fieldOfStudy": "Campo di studio",
            "grade": "Voto",
            "activities": "Attività",
            "proficiency": "Livello di competenza",
            "beginner": "Principiante",
            "intermediate": "Intermedio",
            "advanced": "Avanzato",
            "fluent": "Fluente",
            "native": "Madrelingua",
            "credentialID": "ID credenziale",
            "issuingOrganization": "Organizzazione emittente",
            "issueDate": "Data di emissione",
            "expirationDate": "Data di scadenza",
            "noExpiration": "Nessuna scadenza",
            "projectName": "Nome del progetto",
            "projectURL": "URL del progetto",
            "profilePreview": "Anteprima del profilo",
            "profileStrength": "Forza del profilo",
            "profileCompletion": "Completezza del profilo",
            "basicInfo": "Informazioni di base",
            "viewAs": "Visualizza come",
            "publicProfile": "Profilo pubblico",
            "urlSlug": "Slug URL",
            "customURL": "URL personalizzato"
        }
    }
}

# Enrichir les fichiers existants
print("Enrichissement des fichiers de traduction pour la section 'profile'...")
for lang, content in profile_translations.items():
    file_path = f"public/locales/{lang}/common.json"
    existing_data = load_json(file_path)
    
    # Fusion des données (priorité aux nouvelles)
    for section, values in content.items():
        if section not in existing_data:
            existing_data[section] = {}
        existing_data[section].update(values)
    
    # Sauvegarde du fichier enrichi
    save_json(file_path, existing_data)
    print(f"Fichier {file_path} enrichi avec succès")

print("\nEnrichissement terminé pour la section 'profile'.")
