# Configuration Netlify simplifiée
[build]
  command = "npm ci --no-audit --no-fund --loglevel=error && export NODE_OPTIONS=\"--max-old-space-size=4096\" && node fix-router-imports.js && npm run build:netlify && node update-brand.js"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "9.8.0"
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_PNPM = "false"

# Configuration de base des fonctions
[functions]
  directory = "functions"
  node_bundler = "esbuild"

# Configuration des redirections
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuration du cache
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
