"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PrivacyPolicy = PrivacyPolicy;
const jsx_runtime_1 = require("react/jsx-runtime");
const react_i18next_1 = require("react-i18next");
function PrivacyPolicy() {
    const { t } = (0, react_i18next_1.useTranslation)();
    return ((0, jsx_runtime_1.jsx)("div", { className: "max-w-4xl mx-auto py-12 px-4 sm:px-6 lg:px-8", children: (0, jsx_runtime_1.jsxs)("div", { className: "prose prose-invert max-w-none", children: [(0, jsx_runtime_1.jsx)("h1", { children: t('privacy.title') }), (0, jsx_runtime_1.jsx)("h2", { children: t('privacy.dataCollection.title') }), (0, jsx_runtime_1.jsx)("p", { children: t('privacy.dataCollection.description') }), (0, jsx_runtime_1.jsxs)("ul", { children: [(0, jsx_runtime_1.jsx)("li", { children: t('privacy.dataCollection.personal') }), (0, jsx_runtime_1.jsx)("li", { children: t('privacy.dataCollection.preferences') }), (0, jsx_runtime_1.jsx)("li", { children: t('privacy.dataCollection.skills') }), (0, jsx_runtime_1.jsx)("li", { children: t('privacy.dataCollection.usage') })] }), (0, jsx_runtime_1.jsx)("h2", { children: t('privacy.dataPurpose.title') }), (0, jsx_runtime_1.jsx)("p", { children: t('privacy.dataPurpose.description') }), (0, jsx_runtime_1.jsxs)("ul", { children: [(0, jsx_runtime_1.jsx)("li", { children: t('privacy.dataPurpose.matching') }), (0, jsx_runtime_1.jsx)("li", { children: t('privacy.dataPurpose.recommendations') }), (0, jsx_runtime_1.jsx)("li", { children: t('privacy.dataPurpose.analytics') })] }), (0, jsx_runtime_1.jsx)("h2", { children: t('privacy.dataRetention.title') }), (0, jsx_runtime_1.jsx)("p", { children: t('privacy.dataRetention.description') }), (0, jsx_runtime_1.jsxs)("ul", { children: [(0, jsx_runtime_1.jsx)("li", { children: t('privacy.dataRetention.preferences') }), (0, jsx_runtime_1.jsx)("li", { children: t('privacy.dataRetention.skills') }), (0, jsx_runtime_1.jsx)("li", { children: t('privacy.dataRetention.logs') })] }), (0, jsx_runtime_1.jsx)("h2", { children: t('privacy.security.title') }), (0, jsx_runtime_1.jsx)("p", { children: t('privacy.security.description') }), (0, jsx_runtime_1.jsxs)("ul", { children: [(0, jsx_runtime_1.jsx)("li", { children: t('privacy.security.encryption') }), (0, jsx_runtime_1.jsx)("li", { children: t('privacy.security.access') }), (0, jsx_runtime_1.jsx)("li", { children: t('privacy.security.monitoring') }), (0, jsx_runtime_1.jsx)("li", { children: t('privacy.security.compliance') })] }), (0, jsx_runtime_1.jsx)("h2", { children: t('privacy.rights.title') }), (0, jsx_runtime_1.jsx)("p", { children: t('privacy.rights.description') }), (0, jsx_runtime_1.jsxs)("ul", { children: [(0, jsx_runtime_1.jsx)("li", { children: t('privacy.rights.access') }), (0, jsx_runtime_1.jsx)("li", { children: t('privacy.rights.rectification') }), (0, jsx_runtime_1.jsx)("li", { children: t('privacy.rights.erasure') }), (0, jsx_runtime_1.jsx)("li", { children: t('privacy.rights.portability') }), (0, jsx_runtime_1.jsx)("li", { children: t('privacy.rights.withdraw') })] }), (0, jsx_runtime_1.jsx)("h2", { children: t('privacy.contact.title') }), (0, jsx_runtime_1.jsx)("p", { children: t('privacy.contact.description') })] }) }));
}
