import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import ToastContainer from './ToastContainer';
import { DashboardLayout } from './components/DashboardLayout';
import { JobSearch } from './components/JobSearch';
import { MarketAnalysis } from './components/MarketAnalysis';
import { Dashboard } from './components/Dashboard';
import { JobApplications } from './components/JobApplications';
import { Auth } from './components/Auth';
import Pricing from './components/Pricing';
import { Profile } from './components/Profile';
import { PrivacyPolicy } from './components/PrivacyPolicy';
import { PrivacyConsent } from './components/PrivacyConsent';
import { SecurityBadge } from './components/SecurityBadge';
import { ProtectedRoute } from './components/ProtectedRoute';
import { AuthProvider } from './components/AuthProvider';
import { CVBuilder } from './components/cv/CVBuilder';
import { NetworkPage } from './components/NetworkPage';
import JobNexAILanding from './components/JobNexAILanding';
import FeaturesPage from './components/pages/FeaturesPage';
import { HowItWorksPage } from './components/pages/HowItWorksPage';
import { TestimonialsPage } from './components/pages/TestimonialsPage';
import { ResetPassword } from './components/ResetPassword';
import { AuthCallback } from './components/AuthCallback';
import { FreelanceProjects } from './components/freelance/FreelanceProjects';
import { FreelanceProfile } from './components/freelance/FreelanceProfile';
import MarketTrendsPage from './components/pages/MarketTrendsPage';
import { RecruiterDashboard } from './components/recruiter/RecruiterDashboard';
import { CandidateSearch } from './components/recruiter/CandidateSearch';
import { JobPostings } from './components/recruiter/JobPostings';
import { CreateJobPosting } from './components/recruiter/CreateJobPosting';
import { UserTypeSelection } from './components/UserTypeSelection';
import { ErrorBoundary } from './components/ErrorBoundary';
import { StripeCheckoutStatus } from './components/StripeCheckoutStatus';
import { Billing } from './components/Billing';
import { SubscriptionBanner } from './components/SubscriptionBanner';
function App() {
    return (_jsx(ErrorBoundary, { children: _jsx(Router, { children: _jsxs(AuthProvider, { children: [_jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(JobNexAILanding, {}) }), _jsx(Route, { path: "/login", element: _jsx(Auth, {}) }), _jsx(Route, { path: "/pricing", element: _jsx(Pricing, {}) }), _jsx(Route, { path: "/privacy", element: _jsx(PrivacyPolicy, {}) }), _jsx(Route, { path: "/features", element: _jsx(FeaturesPage, {}) }), _jsx(Route, { path: "/how-it-works", element: _jsx(HowItWorksPage, {}) }), _jsx(Route, { path: "/testimonials", element: _jsx(TestimonialsPage, {}) }), _jsx(Route, { path: "/auth/reset-password", element: _jsx(ResetPassword, {}) }), _jsx(Route, { path: "/auth/callback", element: _jsx(AuthCallback, {}) }), _jsx(Route, { path: "/checkout/success", element: _jsx(StripeCheckoutStatus, {}) }), _jsx(Route, { path: "/user-type", element: _jsx(ProtectedRoute, { children: _jsx(UserTypeSelection, {}) }) }), _jsxs(Route, { element: _jsx(ProtectedRoute, { children: _jsx(DashboardLayout, {}) }), children: [_jsx(Route, { path: "/dashboard", element: _jsx(Dashboard, {}) }), _jsx(Route, { path: "/profile", element: _jsx(Profile, {}) }), _jsx(Route, { path: "/billing", element: _jsx(Billing, {}) }), _jsx(Route, { path: "/jobs", element: _jsx(ProtectedRoute, { requiresSubscription: true, children: _jsx(JobSearch, {}) }) }), _jsx(Route, { path: "/applications", element: _jsx(ProtectedRoute, { requiresSubscription: true, children: _jsx(JobApplications, {}) }) }), _jsx(Route, { path: "/market-analysis", element: _jsx(ProtectedRoute, { requiresSubscription: true, children: _jsx(MarketAnalysis, {}) }) }), _jsx(Route, { path: "/cv-builder", element: _jsx(ProtectedRoute, { requiresSubscription: true, children: _jsx(CVBuilder, {}) }) }), _jsx(Route, { path: "/network", element: _jsx(ProtectedRoute, { requiresSubscription: true, children: _jsx(NetworkPage, {}) }) }), _jsx(Route, { path: "/market-trends", element: _jsx(ProtectedRoute, { requiresSubscription: true, children: _jsx(MarketTrendsPage, {}) }) }), _jsx(Route, { path: "/freelance/projects", element: _jsx(ProtectedRoute, { requiresSubscription: true, children: _jsx(FreelanceProjects, {}) }) }), _jsx(Route, { path: "/freelance/profile", element: _jsx(ProtectedRoute, { requiresSubscription: true, children: _jsx(FreelanceProfile, {}) }) }), _jsx(Route, { path: "/recruiter/dashboard", element: _jsx(ProtectedRoute, { requiresSubscription: true, children: _jsx(RecruiterDashboard, {}) }) }), _jsx(Route, { path: "/recruiter/candidates", element: _jsx(ProtectedRoute, { requiresSubscription: true, children: _jsx(CandidateSearch, {}) }) }), _jsx(Route, { path: "/recruiter/job-postings", element: _jsx(ProtectedRoute, { requiresSubscription: true, children: _jsx(JobPostings, {}) }) }), _jsx(Route, { path: "/recruiter/create-job", element: _jsx(ProtectedRoute, { requiresSubscription: true, children: _jsx(CreateJobPosting, {}) }) })] })] }), _jsx(PrivacyConsent, {}), _jsx(SecurityBadge, {}), _jsx(SubscriptionBanner, {}), _jsx(ToastContainer, {})] }) }) }));
}
export default App;
